/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.StoragedDrugDAO;
import helper.DateHelper;
import helper.JdbcHelper;
import helper.ShareHelper;
import java.sql.ResultSet;
import java.util.Date;
import java.util.List;
import model.StoragedDrug;

/**
 *
 * @author Admin
 */
public class DrugStatus extends javax.swing.JInternalFrame
{

    /** Creates new form DrugStatus */
    public DrugStatus()
    {
        initComponents();
        init();
    }

    /** This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblReview = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRevenue_Sale_No = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRevenue_Sale_Cash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRevenue_Sale_Debit = new javax.swing.JTextField();
        txtRevenue_Sale_Total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtEXP_type_7day = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEXP_type_7day_revoke = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEXP_type_1day_revoke = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEXP_type_1day = new javax.swing.JTextField();

        jScrollPane3.setBorder(null);

        tblReview.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblReview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        tblReview.setRowHeight(30);
        jScrollPane3.setViewportView(tblReview);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doanh số", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Số đơn bán");

        txtRevenue_Sale_No.setEditable(false);

        jLabel4.setText("Doanh thu tiền mặt");

        txtRevenue_Sale_Cash.setEditable(false);

        jLabel6.setText("Doanh thu thẻ");

        txtRevenue_Sale_Debit.setEditable(false);

        txtRevenue_Sale_Total.setEditable(false);

        jLabel8.setText("Tổng doanh thu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRevenue_Sale_No, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txtRevenue_Sale_Cash)
                    .addComponent(txtRevenue_Sale_Debit)
                    .addComponent(txtRevenue_Sale_Total))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRevenue_Sale_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRevenue_Sale_Cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRevenue_Sale_Debit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRevenue_Sale_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thuốc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtEXP_type_7day.setEditable(false);

        jLabel10.setText("Số loại huốc hết hạn trong 7 ngày");

        txtEXP_type_7day_revoke.setEditable(false);

        jLabel11.setText("Số lượng thuốc hết hạn trong 7 ngày");

        txtEXP_type_1day_revoke.setEditable(false);

        jLabel12.setText("Số lượng thuốc hết hạn trong ngày");

        jLabel13.setText("Số loại thuốc hết hạn trong ngày");

        txtEXP_type_1day.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEXP_type_7day_revoke, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEXP_type_1day_revoke, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEXP_type_1day, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEXP_type_7day, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEXP_type_1day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEXP_type_1day_revoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEXP_type_7day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEXP_type_7day_revoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    StoragedDrugDAO dao= new StoragedDrugDAO();
    List<StoragedDrug> list1, list2;
    
    void init()
    {
        setFrameIcon(ShareHelper.APP_ICON);
        load();
    }
    
    public void load()
    {
        try
        {
            ResultSet rs1 = JdbcHelper.executeQuery("Select COUNT(DISTINCT MaTHUOC), sum(soluongton) from THUOCTRONGKHO WHERE MADAILY = '"+ShareHelper.Branch.getBranchID()+"' and ngayhethan between '"+ DateHelper.toString(DateHelper.now())+"' and '"+DateHelper.toString(DateHelper.addDays(DateHelper.now(), 7))+"'");
            System.out.println(DateHelper.toString(DateHelper.addDays(DateHelper.now(), 7)));
            while (rs1.next())
            {
                txtEXP_type_7day.setText(rs1.getString(1));
                txtEXP_type_7day_revoke.setText(rs1.getString(2));
            }
            
             rs1 = JdbcHelper.executeQuery("Select COUNT(DISTINCT MaTHUOC), sum(soluongton) from THUOCTRONGKHO WHERE MADAILY = '"+ShareHelper.Branch.getBranchID()+"' and ngayhethan = '"+ DateHelper.toString(DateHelper.now())+"'");
            while (rs1.next())
            {
                txtEXP_type_1day.setText(rs1.getString(1));
                txtEXP_type_1day_revoke.setText(rs1.getString(2));
            }
            
            rs1= JdbcHelper.executeQuery("Select COUNT(DISTINCT H.MaHDBan), SUM(T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '"+ShareHelper.Branch.getBranchID()+"' and ngayban = '"+ DateHelper.toString(DateHelper.now())+"'");
            while(rs1.next())
            {
                txtRevenue_Sale_No.setText(rs1.getString(1));
                txtRevenue_Sale_Total.setText(rs1.getString(2));
            }
            
            rs1= JdbcHelper.executeQuery("Select  SUM(T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '"+ShareHelper.Branch.getBranchID()+"' and ngayban = '"+ DateHelper.toString(DateHelper.now())+"' AND HINHTHUCTHANHTOAN = 'CASH'");
            while(rs1.next())
            {
                txtRevenue_Sale_Cash.setText(rs1.getString(1));
            }
            
            rs1= JdbcHelper.executeQuery("Select  SUM(T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '"+ShareHelper.Branch.getBranchID()+"' and ngayban = '"+ DateHelper.toString(DateHelper.now())+"' AND HINHTHUCTHANHTOAN = 'DEBIT'");
            while(rs1.next())
            {
                txtRevenue_Sale_Debit.setText(rs1.getString(1));
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public void fillEXP()
    {
        list1=null;
        list1=dao.select("Select * from THUOCTRONG KHO WHERE MADAILY = "+ShareHelper.Branch.getBranchID()+" and ngayhethan between "+ DateHelper.now()+" and "+DateHelper.addDays(DateHelper.now(), 7));
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblReview;
    private javax.swing.JTextField txtEXP_type_1day;
    private javax.swing.JTextField txtEXP_type_1day_revoke;
    private javax.swing.JTextField txtEXP_type_7day;
    private javax.swing.JTextField txtEXP_type_7day_revoke;
    private javax.swing.JTextField txtRevenue_Sale_Cash;
    private javax.swing.JTextField txtRevenue_Sale_Debit;
    private javax.swing.JTextField txtRevenue_Sale_No;
    private javax.swing.JTextField txtRevenue_Sale_Total;
    // End of variables declaration//GEN-END:variables





}
