/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.StoragedDrugDAO;
import helper.DateHelper;
import helper.DialogHelper;
import helper.JdbcHelper;
import helper.ShareHelper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.StoragedDrug;

/**
 *
 * @author Admin
 */
public class StoreStatus extends javax.swing.JInternalFrame
{

    /** Creates new form DrugStatus */
    public StoreStatus()
    {
        initComponents();
        init();
    }

    /** This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSale = new javax.swing.JTable();
        cbbSales = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDrug = new javax.swing.JTable();
        cbbDrug = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNoType = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoUnit = new javax.swing.JFormattedTextField();
        txtRevoke = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRevoke = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doanh số", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jScrollPane4.setBorder(null);

        tblSale.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Invoice ID", "Time", "Sales", "Payment method", "Discount", "Total bill", "Status"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblSale.setRowHeight(30);
        jScrollPane4.setViewportView(tblSale);

        cbbSales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today sales invoices", "Today revoke sales invoices" }));
        cbbSales.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbbSalesActionPerformed(evt);
            }
        });

        jLabel1.setText("Total income");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("VND #,##0"))));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel2.setText("Total invoice");

        jLabel3.setText("Total revoke invoice");

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbbSales, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4))
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cbbSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thuốc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jScrollPane3.setBorder(null);

        tblDrug.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Drug ID", "Drug Name", "Batch no", "Stored Quantity", "Unit", "Date import", "Date of manufactored", "Date of exp", "Status"
            }
        ));
        tblDrug.setRowHeight(30);
        jScrollPane3.setViewportView(tblDrug);

        cbbDrug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All drugs", "Today expired drugs", "7 days expired drugs", "Today revoked drugs", "7 days revoked drugs" }));
        cbbDrug.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbbDrugActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount of type");

        txtNoType.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Amount of unit");

        txtNoUnit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtRevoke.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel6.setText("Total revoked drugs");

        btnRevoke.setText("Revoke drug");
        btnRevoke.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRevokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoType, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRevoke, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRevoke)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRevoke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtRevoke, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtNoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtNoType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void load()
    {
        modelDrug = (DefaultTableModel) tblDrug.getModel();
        modelSales = (DefaultTableModel) tblSale.getModel();

        getDrug(DateHelper.toDate("1/1/3000"), false);
        getInvoices(false);
    }
    private void cbbDrugActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbbDrugActionPerformed
    {//GEN-HEADEREND:event_cbbDrugActionPerformed
        switch (cbbDrug.getSelectedIndex())
        {
            case 0:
                getDrug(DateHelper.toDate("1/1/3000"), false);
                break;
            case 1:
                getDrug(DateHelper.now(), false);
                break;
            case 2:
                getDrug(DateHelper.addDays(DateHelper.now(), 7), false);
                break;
            case 3:
                getDrug(DateHelper.now(), true);
                break;
            case 4:
                getDrug(DateHelper.addDays(DateHelper.now(), 7), true);
                break;
        }


    }//GEN-LAST:event_cbbDrugActionPerformed

    private void btnRevokeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRevokeActionPerformed
    {//GEN-HEADEREND:event_btnRevokeActionPerformed
        new ConfirmDeleteHelper(ShareHelper.frame, true).setVisible(true);
        if (ShareHelper.status != null)
        {
            StoragedDrug model = dao.findById(tblDrug.getValueAt(tblDrug.getSelectedRow(), 0).toString());
            model.setStatus(ShareHelper.getStatus());
            try
            {
                dao.update(model);
                load();
                DialogHelper.alert(this, "Revoke successfully");
                ShareHelper.status = null;
            } catch (Exception e)
            {
                e.printStackTrace();
                DialogHelper.alert(this, "Update failed!");
            }
        }
    }//GEN-LAST:event_btnRevokeActionPerformed

    private void cbbSalesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbbSalesActionPerformed
    {//GEN-HEADEREND:event_cbbSalesActionPerformed
        switch (cbbSales.getSelectedIndex())
        {
            case 0:
                getInvoices(false);
                break;
            case 1:
                getInvoices(true);
                break;

        }
    }//GEN-LAST:event_cbbSalesActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        load();
    }//GEN-LAST:event_formInternalFrameOpened

    StoragedDrugDAO dao = new StoragedDrugDAO();
    DefaultTableModel modelDrug, modelSales;
    List<StoragedDrug> list1;
    ResultSet list2;
    int i = 1;
    String[][] arr;

    void init()
    {
        setFrameIcon(ShareHelper.APP_ICON);

        list2 = JdbcHelper.executeQuery("Select H.MAHDBAN, NGAYBAN, HINHTHUCTHANHTOAN, SUM(T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '" + ShareHelper.Branch.getBranchID() + "' and ngayban = '" + DateHelper.toString(DateHelper.now()) + "' GROUP BY H.MAHDBAN, NGAYBAN, HINHTHUCTHANHTOAN");
    }

    public void getDrug(Date date, boolean exp)
    {
        String sql = "Select * from THUOCTRONGKHO JOIN Thuoc on thuoc.mathuoc=thuoctrongkho.mathuoc WHERE MADAILY = '" + ShareHelper.Branch.getBranchID() + "' and ngayhethan between '" + DateHelper.toString(DateHelper.now()) + "' and '" + DateHelper.toString(date) + "'";
        if (exp)
        {
            sql += " and trangthaithuoc is not null";
        }
        ResultSet rs = JdbcHelper.executeQuery(sql);
        int total_unit = 0, total_type = 0, total_revoke = 0;
        Set type = new HashSet();

        modelDrug.setRowCount(0);
        try
        {
            while (rs.next())
            {
                Object[] row =
                {
                    rs.getString("MATHUOC"),
                    rs.getString("tenthuoc"),
                    rs.getString("MaLoHang"),
                    rs.getInt("soluongton"),
                    rs.getString("donvitinh"),
                    rs.getDate("ngaynhaphang"),
                    rs.getDate("ngaysx"),
                    rs.getDate("ngayhethan"),
                    rs.getString("trangthaithuoc"),
                };
                type.add(rs.getString("MATHUOC"));
                total_unit += rs.getInt("soluongton");
                if (rs.getString("trangthaithuoc") != null)
                {
                    total_revoke += 1;
                }

                modelDrug.addRow(row);
            }
        } catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        txtNoType.setText(String.valueOf(type.size()));
        txtNoUnit.setText(String.valueOf(total_unit));
        txtRevoke.setText(String.valueOf(total_revoke));
    }

    public void getInvoices(Boolean exp)
    {
        String sql = "Select H.MAHDBAN, NGAYBAN, MANV, HINHTHUCTHANHTOAN, GIAMGIA, NGAYNHAPHANG, trangthaihdban, SUM (T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '" + ShareHelper.Branch.getBranchID() + "' and ngayban between '" + DateHelper.toString(null,"yyyy/MM/dd") + " 00:00:00' and '"+DateHelper.toString(null,"yyyy/MM/dd")+" 23:59:59'";
        System.out.println(sql);

        if (exp)
        {
            sql += " and trangthaihdban is not null GROUP BY H.MAHDBAN, NGAYBAN, MANV, HINHTHUCTHANHTOAN, GIAMGIA, NGAYNHAPHANG, trangthaihdban";
        }
        else
            sql+= "GROUP BY H.MAHDBAN, NGAYBAN, MANV, HINHTHUCTHANHTOAN, GIAMGIA, NGAYNHAPHANG, trangthaihdban";
        ResultSet rs = JdbcHelper.executeQuery(sql);
        modelSales.setRowCount(0);
        try
        {
            while (rs.next())
            {
                Object[] row =
                {
                    rs.getString("MAHDBAN"),
                    rs.getTime("NGAYBAN"),
                    rs.getString("MaNV"),
                    rs.getString("HINHTHUCTHANHTOAN"),
                    rs.getInt("GIAMGIA"),
                    rs.getDate("ngaynhaphang"),
                    rs.getString("trangthaihdban"),
                };

                modelSales.addRow(row);
            }
        } catch (SQLException ex)
        {
            ex.printStackTrace();
        }

    }

//    public void load()
//    {
//        
//            
//
//           
//
//            rs1 = JdbcHelper.executeQuery("Select COUNT(DISTINCT H.MaHDBan), SUM(T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '" + ShareHelper.Branch.getBranchID() + "' and ngayban = '" + DateHelper.toString(DateHelper.now()) + "'");
//            while (rs1.next())
//            {
//                txtRevenue_Sale_No.setText(rs1.getString(1));
//                txtRevenue_Sale_Total.setText(rs1.getString(2));
//            }
//
//            rs1 = JdbcHelper.executeQuery("Select  SUM(T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '" + ShareHelper.Branch.getBranchID() + "' and ngayban = '" + DateHelper.toString(DateHelper.now()) + "' AND HINHTHUCTHANHTOAN = 'CASH'");
//            while (rs1.next())
//            {
//                txtRevenue_Sale_Cash.setText(rs1.getString(1));
//            }
//
//            rs1 = JdbcHelper.executeQuery("Select  SUM(T.GiaBan*HCT.SOLUONG) from HOADONBANHANG as H JOIN HoaDonBanHangChiTiet as HCT on H.MaHDBan=HCT.MaHDBan JOIN ThuocTrongKho AS T ON T.IDThuoc=HCT.IDThuoc WHERE MADAILY = '" + ShareHelper.Branch.getBranchID() + "' and ngayban = '" + DateHelper.toString(DateHelper.now()) + "' AND HINHTHUCTHANHTOAN = 'DEBIT'");
//            while (rs1.next())
//            {
//                txtRevenue_Sale_Debit.setText(rs1.getString(1));
//            }
//        } catch (Exception e)
//        {
//            e.printStackTrace();
//        }
//    }
//    public void fillSale()
//    {
//        try
//        {
//            tblDrug = new JTable();
//            tblDrug.setFont(new java.awt.Font("Dialog", 0, 14));
//            DefaultTableModel model = new DefaultTableModel(new Object[]
//            {
//                "Mã hóa đơn", "Ngày bán", "Hình thức thanh toán", "Tổng tiền"
//            }, 0);
//            tblDrug.setRowHeight(30);
//            jScrollPane3.setViewportView(tblDrug);
//            tblDrug.setModel(model);
//
//            for (int j = 1; j < i; j++)
//            {
//                model.addRow(new Object[]
//                {
//                    arr[0][j], arr[1][j], arr[2][j], arr[3][j]
//                });
//            }
//
//        } catch (Exception e)
//        {
//            e.printStackTrace();
//        }
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevoke;
    private javax.swing.JComboBox<String> cbbDrug;
    private javax.swing.JComboBox<String> cbbSales;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDrug;
    private javax.swing.JTable tblSale;
    private javax.swing.JFormattedTextField txtNoType;
    private javax.swing.JFormattedTextField txtNoUnit;
    private javax.swing.JFormattedTextField txtRevoke;
    // End of variables declaration//GEN-END:variables

}
