
CREATE DATABASE PharmaSystemManager
GO
USE PharmaSystemManager
go

CREATE TABLE LoaiThuoc
(
	MaLoaiThuoc NVARCHAR(10) NOT NULL,
	TenLoaiThuoc NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(MAX)
	CONSTRAINT PK_LoaiThuoc PRIMARY KEY(MaLoaiThuoc)
)

CREATE TABLE DaiLy
(
	MaDaiLy NVARCHAR(10) NOT NULL,
	TenDaiLy NVARCHAR(100) NOT NULL,
	EmailDaiLy NVARCHAR(50) NOT NULL,
	SDTDaiLy NVARCHAR(15) NOT NULL,
	DiaChiDaiLy NVARCHAR(50) NOT NULL,
	ThanhPhoDaiLy NVARCHAR(50) NOT NULL,
	TrangThaiDaiLy NVARCHAR(50) NULL
	CONSTRAINT PK_DaiLy PRIMARY KEY(MaDaiLy)
)
CREATE TABLE NhaCungCap
(
	MaNCC NVARCHAR(10) NOT NULL,
	TenNCC NVARCHAR(100) NOT NULL,
	EmailNCC NVARCHAR(50) NOT NULL,
	SDTNCC NVARCHAR(15) NOT NULL,
	DiaChiNCC NVARCHAR(50) NOT NULL,
	ThanhPhoNCC NVARCHAR(50) NOT NULL,
	Mota NVARCHAR(MAX) NOT NULL,
	TrangThaiNCC NVARCHAR(50) NULL
	CONSTRAINT PK_NhaCungCap PRIMARY KEY(MaNCC)
)

CREATE TABLE Thuoc
(
	MaThuoc NVARCHAR(10) NOT NULL,
	TenThuoc NVARCHAR(100) NOT NULL,
	TenKhoaHoc NVARCHAR(50) NOT NULL,
	NhietDoBaoQuan INT NOT NULL,
	QuyCachDongGoi NVARCHAR(50) NOT NULL,
	DonViTinh NVARCHAR(10) NOT NULL,
	NhaSX NVARCHAR(50) NOT NULL,
	MoTaThuoc NVARCHAR(MAX) NOT NULL,
	TrangThaiThuoc NVARCHAR(50) NULL,
	MaLoaiThuoc NVARCHAR(10) NOT NULL,
	CONSTRAINT PK_Thuoc PRIMARY KEY(MaThuoc),
	CONSTRAINT FK_Thuoc_LoaiThuoc FOREIGN KEY(MaLoaiThuoc) REFERENCES LoaiThuoc
)

CREATE TABLE NhanVien
(
	MaNV NVARCHAR(10) NOT NULL,
	MatKhau NVARCHAR(50) NOT NULL,
	VaiTro BIT NOT NULL,
	HoVaTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	NgayLamViec DATE NOT NULL,
	SDTNV NVARCHAR(15) NOT NULL,
	EmailNV NVARCHAR(50) NOT NULL,
	DiaChiNV NVARCHAR(50) NOT NULL,
	TrangThaiNV NVARCHAR(50) NULL,
	MaDaiLy NVARCHAR(10) NOT NULL
	CONSTRAINT PK_NhanVien PRIMARY KEY(MaNV),
	CONSTRAINT FK_NhanVien FOREIGN KEY(MaDaiLy) REFERENCES DaiLy
)

CREATE TABLE ThuocTrongKho
(
	IDThuoc INT IDENTITY(100, 1) NOT NULL,
	MaLoHang NVARCHAR(10) NOT NULL,
	NgaySX DATE NOT NULL,
	NgayHetHan DATE NOT NULL,
	SoLuong INT NOT NULL,
	NgayNhapHang DATE NOT NULL,
	GiaBan MONEY NOT NULL,
	GiaNhap MONEY NOT NULL,
	MaThuoc NVARCHAR(10) NOT NULL,
	MaDaiLy NVARCHAR(10) NOT NULL,
	CONSTRAINT PK_ThuocTrongKho PRIMARY KEY(IDThuoc),
	CONSTRAINT FK_ThuocTrongKho_Thuoc FOREIGN KEY(MaThuoc) REFERENCES Thuoc,
	CONSTRAINT FK_ThuocTrongKho_DaiLy FOREIGN KEY(MaDaiLy) REFERENCES DaiLy
)

CREATE FUNCTION AUTO_MaHDMua()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MaHDMua) FROM HoaDonThuMua) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHDMua, 3)) FROM HoaDonThuMua
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDM00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDM0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

CREATE TABLE HoaDonThuMua
(
	MaHDMua NVARCHAR(10) PRIMARY KEY CONSTRAINT PK_HoaDonThuMua DEFAULT DBO.AUTO_MaHDMua(),
	NgayMua DATE NOT NULL,
	HinhThucThanhToan NVARCHAR(50) NOT NULL,
	GiamGia INT NOT NULL,
	SoTienThanhToan MONEY NOT NULL,
	SoTienConLai Money NOT NULL,
	TrangThaiHDMua NVARCHAR(50) NULL,
	MaNV NVARCHAR(10) NOT NULL,
	MaNCC NVARCHAR(10) NOT NULL,
	CONSTRAINT FK_HoaDonThuMua_NhanVien FOREIGN KEY(MaNV) REFERENCES NhanVien,
	CONSTRAINT FK_HoaDonThuMua_NhaCungCap FOREIGN KEY(MaNCC) REFERENCES NhaCungCap
)

CREATE TABLE HoaDonThuMuaChiTiet
(
	MaHDMua NVARCHAR(10) NOT NULL,
	IDThuoc INT NOT NULL,
	CONSTRAINT PK_HoaDonThuMuaChiTiet PRIMARY KEY(MaHDMua, IDThuoc),
	CONSTRAINT FK_PK_HoaDonThuMuaChiTiet_HoaDonThuMua FOREIGN KEY(MaHDMua) REFERENCES HoaDonThuMua,
	CONSTRAINT FK_PK_HoaDonThuMuaChiTiet_ThuocTrongKho FOREIGN KEY(IDThuoc) REFERENCES ThuocTrongKho
)


CREATE FUNCTION AUTO_MaHDBan()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MaHDBan) FROM HoaDonBanHang) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHDBan, 3)) FROM HoaDonBanHang
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDB00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDB0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

CREATE TABLE HoaDonBanHang
(
	MaHDBan NVARCHAR(10) PRIMARY KEY CONSTRAINT PK_HoaDonBanHang DEFAULT DBO.AUTO_MaHDBan(),
	NgayBan DATE NOT NULL,
	HinhThucThanhToan NVARCHAR(50) NOT NULL,
	GiamGia INT NOT NULL,
	TrangThaiHDBan NVARCHAR(50) NULL,
	MaNV NVARCHAR(10) NOT NULL,
	CONSTRAINT FK_HoaDonBanHang_NhanVien FOREIGN KEY(MaNV) REFERENCES NhanVien
)

CREATE TABLE HoaDonBanHangChiTiet
(
	MaHDBan NVARCHAR(10) NOT NULL,
	IDThuoc INT NOT NULL,
	CONSTRAINT PK_HoaDonBanHangChiTiet PRIMARY KEY(MaHDBan, IDThuoc),
	CONSTRAINT FK_HoaDonBanHangChiTiet_HoaDonThuMua FOREIGN KEY(MaHDBan) REFERENCES HoaDonBanHang,
	CONSTRAINT FK_HoaDonBanHangChiTiet_ThuocTrongKho FOREIGN KEY(IDThuoc) REFERENCES ThuocTrongKho
)

